import type { NextConfig } from "next";
import fs from "fs";
import path from "path";

/**
 * Consolidation redirects.
 *
 * The article generator used to emit four near-identical pages per topic
 * ("Complete guide: X and Grüns", "Why Grüns for X?", ...), which split ranking
 * authority and left money queries stranded on page 2+ — "grüns vs ritual
 * multivitamin" had six competing pages and zero clicks. The duplicates were
 * removed and each one 301s to the surviving page so the indexed URLs keep
 * their equity instead of 404ing.
 *
 * Map is generated by scripts/consolidate.py -> content/redirects.json.
 */
function articleRedirects() {
  const mapPath = path.join(process.cwd(), "content", "redirects.json");
  if (!fs.existsSync(mapPath)) return [];
  try {
    const map: Record<string, string> = JSON.parse(
      fs.readFileSync(mapPath, "utf-8")
    );
    return Object.entries(map).map(([from, to]) => ({
      source: `/articles/${from}`,
      destination: `/articles/${to}`,
      permanent: true, // 301 — passes ranking signal to the keeper
    }));
  } catch {
    return [];
  }
}

const nextConfig: NextConfig = {
  async redirects() {
    return [
      ...articleRedirects(),
      {
        // Short, branded affiliate link for YouTube/Reddit/etc — no truncation.
        // Carries the snowball affiliate tag through to gruns.co.
        source: "/vip",
        destination: "https://www.gruns.co/pages/vip?snowball=NICK67621",
        permanent: false, // 302 — keep flexible if the affiliate URL changes
      },
      {
        // Cloaked cruise affiliate link — Reddit hard-blocks dpbolvw.net directly,
        // but allows vercel.app, so cruise posts link here and redirect through.
        source: "/cruise",
        destination: "https://www.dpbolvw.net/click-1-17037666",
        permanent: false,
      },
      {
        source: "/:path*",
        destination: "https://grunsgummies.site/:path*",
        basePath: false,
        permanent: true, // 301 redirect
        has: [
          {
            type: "host",
            value: "www.grunsgummies.site",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
